### ISSUE TITLE
SIM-Deploy-Allow configuring validators from a file

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [genlayerlabs/genlayer-studio#567]
For new deployments, it's necessary to create validators in the Simulator
This process ATM is manually done

We should handle the automatic creation of validators from a JSON file (if no validators exist)

**Comment by cristiam86** [comment]
What about the CLI?

**Comment by YeagerAI-Bulat** [comment]
Can I run CLI in headless mode to create validators for existing simulator deployment?

**Comment by cristiam86** [comment]
Not yet, but it will be possible very soon

**Comment by AgustinRamiroDiaz** [comment]
I think it's better to do from a file or file-like configuration, given that we want to have this automated for deployments with docker-compose (I'm open for other deployment strategies, but I feel that docker compose is the one with less friction right now)

Probably we could do an envvar in json format like

```
SIM_INIT_VALIDATORS='{<configuration goes here>}'
```
